### PR TITLE
PHP 7 Compatibility

### PR DESCRIPTION
**Pull request by donovanhare**
Needed to use this package with PHP 7, so have made the nessersary adjustments to make it backwards compatible.

Let me know if you need me to do anything else.

### CODE REVIEW

**Review by wdelfuego — APPROVED** [review]
Looks good!  I will release version 1.1 containing this update sometime next week.

Thanks a lot for your contribution!

**Comment by wdelfuego** [comment]
Hi @donovanhare, 

Starting with version 1.1 I will switch away from the MIT license and make Nova Calendar available under the following dual licensing model:

> - GNU AGPLv3 for GPL-licensed open source projects. Note that this license is not compatible with usage in Nova, so this package can't be used under this license until a version exists that can be included in Laravel/Vue3 projects without depending on Nova.
> - A 100% free (as in beer, not as in speech) and perpetual do-what-you-want license that allows any and all forms of use, commercial or not, under one condition: if you use the package commercially, you have to be doing so by implementing calendar views that can be used by end users: this license forbids commercial sublicensing or other forms of commercial usage such as supplying (parts of) the package to other developers by including it in a paid-for admin panel framework. You are free to make any modifications you want and are not required to make your modifications public or announce them.

Do you agree to your pull request being included and distributed under this dual licensing model?

I'd be happy to answer any questions or comments you might have.

**Comment by donovanhare** [comment]
Yes, that sounds like a great direction forward. Thank you for checking in with me 👍

**Comment by wdelfuego** [comment]
Great, I will merge and release the update as soon as possible :).
Thanks!

**Comment by wdelfuego** [comment]
I have the merge ready, but need a bit more time to release it -- since the namespace of the dataprovider changes, releasing this update will break backwards compatibility and force me to do a major version bump to 2.0 in order to follow semantic versioning and not break existing installations unexpectedly. I want to make use of that major version bump in order to do some more changes that might break backwards compatibility so I will delay the release of PHP7 support a bit in order to do a nice 2.0 release.

Sorry for the delay; if anyone is eager to run this package under PHP7 already, take a look at the changes in the commits of this pull request and feel free to ask for help in a Discussion.

**Comment by wdelfuego** [comment]
Merged into `dev` branch, PHP7.4 compatibility will be released with 2.0

**Comment by wdelfuego** [comment]
Finally out with the release of 2.0 today :)

Thanks again, @donovanhare !

**Comment by donovanhare** [comment]
Amazing, thank you @wdelfuego :)

**Pull request merged**
